---
title: "Data Manipulation"

output: github_document
---
```{r}
library(tidyverse)

```


##load the FAS Litters Data

```{r}
litters_df = read_csv("./data/FAS_litters.csv") #relative path
litters_df = janitor::clean_names(litters_df)

```

##select
 choose some columns and not others
```{r}
select(litters_df, group, litter_number) #pick columns to keep
#use :: to select a range of columns or , to pck different ones
#to specifiy what to get rid of instead of picking wat to have use -litter_number

```

Renaming columns

```{r}
select(litters_df, GROUP=group, LITTer_NUmber = litter_number) #renaming
rename(litters_df, GROUP=group, LITTer_NUmber = litter_number) #another renaiming more

```

Select helpers

```{r}
select(litters_df, starts_with("gd"))

```

```{r}
select(litters_df, litter_number, everything()) #brings littler number to bring
relocate(litters_df, litter_number)

```

## Filter

```{r}
filter(litters_df, gd0_weight >= 22)
```

```{r}
filter(litters_df, gd_of_birth ==20)
```

```{r}
filter(litters_df, !(gd_of_birth == 20)) #! negates the operation
```


```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth ==20)

```

```{r}
filter(litters_df, group == "Mod8")

```

```{r}
filter(litters_df, group %in% c("Con7", "Mod8")) # or 
```

## mutate

```{r}
mutate(
  litters_df, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)) #override group variable

```

## Arrange

putting things in order

```{r}
arrange(litters_df, pups_born_alive, gd0_weight)
```

## %>% pipe opperator

```{r}
litters_data_raw = read_csv("./data/FAS_litters.csv",col_types = "ccddiiii")
litters_data_clean_names = janitor::clean_names(litters_data_raw)
litters_data_selected_cols = select(litters_data_clean_names, -pups_survive)

litters_data_with_vars = 
  mutate(
    litters_data_selected_cols, 
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group))
 
litters_data_with_vars_without_missing = drop_na(litters_data_with_vars, wt_gain)
litters_data_with_vars_without_missing
```

USE THE PIPE OPPERATOR INSTEAD  

```{r}
litters_df =
  read_csv("./data/FAS_litters.csv") %>% 
  janitor :: clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(wt_gain = gd18_weight - gd0_weight) %>% 
  drop_na(gd0_weight)
  
```

